name: Windows 10 RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Download Getscreen.me
      run: |
        Invoke-WebRequest -Uri "https://app.getscreen.me/download/windows" -OutFile "getscreen.exe"
        Start-Process "getscreen.exe" -ArgumentList "/silent" -Wait

    - name: Show Access Info
      run: |
        Write-Host "تم تثبيت Getscreen.me بنجاح!"
        Write-Host "افتح https://app.getscreen.me/dashboard من أي متصفح"
        Write-Host "وسجّل دخولك بنفس الحساب اللي استخدمته في التثبيت"
        Write-Host "هتلاقي الجهاز ظاهر وتقدر توصّل له مباشرة من المتصفح أو التطبيق"
        while ($true) {
          Write-Host "[$(Get-Date)] RDP Active - استخدم Ctrl+C لإيقاف التشغيل"
          Start-Sleep -Seconds 300
        }
